services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    env_file: .env
    volumes:
      - .:/home/app/web

    command: >
      sh -c 'python manage.py runserver  0.0.0.0:8000'

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
